<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

// Implements HOOK_form_alter
function ec_preview_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_page_edit_form' || 'node_resource_edit_form') {
    $form['#attached']['library'][] = 'ec_preview/preview';
    // Add the button to the node edit form
    if (isset($form["actions"]["preview"])) {
      $form['actions']['preview']['#type'] = 'hidden';
      $form['actions']['ec_preview'] = [
        '#type' => 'link',
        '#title' => t('EC Preview Modal'),
        '#url' => Url::fromRoute('ec_preview.form'),
        '#attributes' => [
          'class' => [
            'button',
            'button--primary'
          ],
        ],
      ];
    }
  }
}
